name: clusternet
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.6.5
  - pytorch=1.2.0
  - numpy=1.16.5
  - igraph=0.7.1
  - networkx=2.3.0
  - scikit-learn=0.21.3
  - jupyterlab
  - matplotlib
  - jupyter
  - pandas
  - torchvision
  - pip